PREFIX ex: <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://example.org/hotel-ontology/1.0.0.3#>

INSERT {
  ?booking a ex:LoyalGuestThisMonth .
}
WHERE {
  ?booking ex:isRepeatedGuest ?rep .

  FILTER(xsd:integer(?rep) = 1)
}