PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/>
PREFIX schema: <http://schema.org/>
PREFIX : <http://example.org/hotel-ontology/1.0.0.3#>

INSERT {
  ?booking a :FamilyBooking .
}
WHERE {
  ?booking schema:numberOfAdults ?adults ;
           ex:children ?children ;
           ex:babies ?babies .

  FILTER(xsd:integer(?adults) > 1 && (xsd:integer(?children) > 0 || xsd:integer(?babies) > 0))
}