PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/>
PREFIX : <http://example.org/hotel-ontology/1.0.0.3#>

INSERT {
  ?booking a :CanceledWithHighADR .
}
WHERE {
  ?booking ex:isCanceled ?canceled ;
           ex:adr ?adr .
  FILTER((?canceled = "1" || ?canceled = "true"^^xsd:boolean) && xsd:decimal(?adr) > 200)
}
