PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/>
PREFIX : <http://example.org/hotel-ontology/1.0.0.3#>

INSERT {
  ?booking a :LongStay .
}
WHERE {
  ?booking ex:weekNights ?w ;
           ex:weekendNights ?we .
  BIND(xsd:integer(?w) + xsd:integer(?we) AS ?total)
  FILTER(?total > 7)
}