PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/>
PREFIX : <http://example.org/hotel-ontology/1.0.0.3#>

INSERT {
  ?booking a :LateSummerBooking .
}
WHERE {
  ?booking ex:arrivalMonth ?m ;
           ex:arrivalDay ?d .
  FILTER(?m = "August" && xsd:integer(?d) > 20)
}
