PREFIX ex: <http://example.org/>
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
  ?booking a :LoyalGuestThisMonth .
}
WHERE {
  ?booking ex:isRepeatedGuest ?rep .

  FILTER(xsd:integer(?rep) = 1)
}