PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/>
PREFIX : <http://example.org/hotel-ontology/1.0.0.3#>

INSERT {
  ?booking a :HighADRBooking .
}
WHERE {
  ?booking ex:adr ?adr .
  FILTER(xsd:decimal(?adr) > 150)
}