PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/>
PREFIX schema: <http://schema.org/>
PREFIX : <http://example.org/hotel-ontology/1.0.0.3#>

INSERT {
  ?booking a :GroupReservation .
}
WHERE {
  ?booking schema:numberOfAdults ?adults ;
           ex:children ?children ;
           ex:babies ?babies .
  BIND(xsd:integer(?adults) + xsd:integer(?children) + xsd:integer(?babies) AS ?total)
  FILTER(?total >= 5 && ?total <= 10)
}
